import express from 'express';
import userRoute from './userRouter';
import authRoute from './authRoute';
import adminRoute from './adminRoute';
import creatorRoute from './creatorRoute';
import companyRoute from './companyRoute';
import eventRoute from './eventRoute';
import campaignRoute from './campaignRoute';
import notificationRoute from './notificationRoute';
import draftRoute from './draftRoute';
import taskRoute from './taskRoute';
import submissionRoute from './submissionRoute';
import submissionV3Route from './submissionV3Route';
import roleRoute from './roleRoute';
import invoiceRoute from './invoiceRoute';
import threadRoute from './threadRoute';
import kanbanRoute from './kanbanRoute';
import bugRoute from './bugRoute';
import accessRoute from './accessRoute';
import packagesRoute from './packageRoutes';
import socialRoute from './socialRoute';
import subscriptionRoute from './subscriptionRoute';
import kwspRoute from './kwspRoute';
import clientRoute from './clientRoute';
import pitchRoute from './pitchRoute';

export const router = express.Router();

router.use('/user', userRoute);
router.use('/auth', authRoute);
router.use('/admin', adminRoute);
router.use('/creator', creatorRoute);
router.use('/company', companyRoute);
router.use('/event', eventRoute);
router.use('/campaign', campaignRoute);
router.use('/notification', notificationRoute);
router.use('/draft', draftRoute);
router.use('/thread', threadRoute);
router.use('/tasks', taskRoute);
router.use('/submission', submissionRoute);
router.use('/submission', submissionV3Route);
router.use('/role', roleRoute);
router.use('/invoice', invoiceRoute);
router.use('/kanban', kanbanRoute);
router.use('/bug', bugRoute);
router.use('/public', accessRoute);
router.use('/package', packagesRoute);
router.use('/social', socialRoute);
router.use('/subscription', subscriptionRoute);
router.use('/kwsp', kwspRoute);
router.use('/client', clientRoute);
router.use('/pitch', pitchRoute);
